plot_ignore_patterns_common:
  - filename_base
  - execution_timestamp
  - datetime
  - date
  - param_hash
  - epoch_id
  - conf_number
  - start_date
  - end_date
  - location
  - comment
  - boundary_overlap
  - station_name
  - source_csv
  - qa_*
  - __*

unexpected_plot_group_name: unexpected
unexpected_group_max_columns: 12
