last_file_test: true
selection:
  stations: [0, 1]
  date_ranges:
    - start: 2024-09-16
      end: 2024-09-30
default_z_positions:
- 0
- 150
- 300
- 450
complete_reanalysis: false
stratos_save: false
# create_plots options: null | debug | usual | all
create_plots: debug
limit_number: null
y_new_method: true
