fast_mode: false
debug_mode: false
last_file_test: true
run_jupyter_notebook: false
jupyter_station_default_task_3: '2'
default_z_positions:
- 0
- 150
- 300
- 450
complete_reanalysis: false
stratos_save: false
create_plots: false
create_essential_plots: false
save_plots: true
create_pdf: false
show_plots: false
create_debug_plots: false
limit: false
limit_number: 10000
limit_fast: false
limit_number_fast: 10000
limit_debug: true
limit_number_debug: 10000
residual_plots_fast: false
charge_front_back_fast: false
charge_front_back_debug: false
time_calibration_fast: false
time_calibration_debug: false
y_new_method: true
timtrack_iteration_fast: false
timtrack_iteration_debug: false
