last_file_test: true
date_range:
  start: null
  end: null
complete_reanalysis: false
force_replacement: true
article_format: false
# create_plots options: null | debug | usual | all
create_plots: all
limit_number: null
EXPECTED_COLUMNS_config: 71
time_window_filtering: true
