last_file_test: true
selection:
  stations: [0, 1]
  date_ranges:
    - start: 2024-09-27
      end: 2024-10-01
complete_reanalysis: false
force_replacement: true
article_format: false
# create_plots options: null | debug | usual | all
create_plots: null
limit_number: null
EXPECTED_COLUMNS_config: 71
time_window_filtering: true
