stations: [0, 1, 2, 3, 4]
task_id: 1
metadata_type: specific
metadata_csv_filename: task_1_metadata_specific.csv
column_patterns_file: task_1_specific_columns.txt
pass_default_value: 1.0
pass_column_name: task_1_specific_pass
column_patterns:
  - 'filename_base'
  - 'execution_timestamp'
  - 'analysis_mode'
  - 'param_hash'
  - 'zeroed_percentage_P1s1'
  - 'zeroed_percentage_P1s2'
  - 'zeroed_percentage_P1s3'
  - 'zeroed_percentage_P1s4'
  - 'zeroed_percentage_P2s1'
  - 'zeroed_percentage_P2s2'
  - 'zeroed_percentage_P2s3'
  - 'zeroed_percentage_P2s4'
  - 'zeroed_percentage_P3s1'
  - 'zeroed_percentage_P3s2'
  - 'zeroed_percentage_P3s3'
  - 'zeroed_percentage_P3s4'
  - 'zeroed_percentage_P4s1'
  - 'zeroed_percentage_P4s2'
  - 'zeroed_percentage_P4s3'
  - 'zeroed_percentage_P4s4'
  - 'T1_F_1_entries_final_rate_hz'
  - 'T1_F_2_entries_final_rate_hz'
  - 'T1_F_3_entries_final_rate_hz'
  - 'T1_F_4_entries_final_rate_hz'
  - 'T1_B_1_entries_final_rate_hz'
  - 'T1_B_2_entries_final_rate_hz'
  - 'T1_B_3_entries_final_rate_hz'
  - 'T1_B_4_entries_final_rate_hz'
  - 'Q1_F_1_entries_final_rate_hz'
  - 'Q1_F_2_entries_final_rate_hz'
  - 'Q1_F_3_entries_final_rate_hz'
  - 'Q1_F_4_entries_final_rate_hz'
  - 'Q1_B_1_entries_final_rate_hz'
  - 'Q1_B_2_entries_final_rate_hz'
  - 'Q1_B_3_entries_final_rate_hz'
  - 'Q1_B_4_entries_final_rate_hz'
  - 'T2_F_1_entries_final_rate_hz'
  - 'T2_F_2_entries_final_rate_hz'
  - 'T2_F_3_entries_final_rate_hz'
  - 'T2_F_4_entries_final_rate_hz'
  - 'T2_B_1_entries_final_rate_hz'
  - 'T2_B_2_entries_final_rate_hz'
  - 'T2_B_3_entries_final_rate_hz'
  - 'T2_B_4_entries_final_rate_hz'
  - 'Q2_F_1_entries_final_rate_hz'
  - 'Q2_F_2_entries_final_rate_hz'
  - 'Q2_F_3_entries_final_rate_hz'
  - 'Q2_F_4_entries_final_rate_hz'
  - 'Q2_B_1_entries_final_rate_hz'
  - 'Q2_B_2_entries_final_rate_hz'
  - 'Q2_B_3_entries_final_rate_hz'
  - 'Q2_B_4_entries_final_rate_hz'
  - 'T3_F_1_entries_final_rate_hz'
  - 'T3_F_2_entries_final_rate_hz'
  - 'T3_F_3_entries_final_rate_hz'
  - 'T3_F_4_entries_final_rate_hz'
  - 'T3_B_1_entries_final_rate_hz'
  - 'T3_B_2_entries_final_rate_hz'
  - 'T3_B_3_entries_final_rate_hz'
  - 'T3_B_4_entries_final_rate_hz'
  - 'Q3_F_1_entries_final_rate_hz'
  - 'Q3_F_2_entries_final_rate_hz'
  - 'Q3_F_3_entries_final_rate_hz'
  - 'Q3_F_4_entries_final_rate_hz'
  - 'Q3_B_1_entries_final_rate_hz'
  - 'Q3_B_2_entries_final_rate_hz'
  - 'Q3_B_3_entries_final_rate_hz'
  - 'Q3_B_4_entries_final_rate_hz'
  - 'T4_F_1_entries_final_rate_hz'
  - 'T4_F_2_entries_final_rate_hz'
  - 'T4_F_3_entries_final_rate_hz'
  - 'T4_F_4_entries_final_rate_hz'
  - 'T4_B_1_entries_final_rate_hz'
  - 'T4_B_2_entries_final_rate_hz'
  - 'T4_B_3_entries_final_rate_hz'
  - 'T4_B_4_entries_final_rate_hz'
  - 'Q4_F_1_entries_final_rate_hz'
  - 'Q4_F_2_entries_final_rate_hz'
  - 'Q4_F_3_entries_final_rate_hz'
  - 'Q4_F_4_entries_final_rate_hz'
  - 'Q4_B_1_entries_final_rate_hz'
  - 'Q4_B_2_entries_final_rate_hz'
  - 'Q4_B_3_entries_final_rate_hz'
  - 'Q4_B_4_entries_final_rate_hz'
  - 'T1_F_1_entries_original_rate_hz'
  - 'T1_F_2_entries_original_rate_hz'
  - 'T1_F_3_entries_original_rate_hz'
  - 'T1_F_4_entries_original_rate_hz'
  - 'T1_B_1_entries_original_rate_hz'
  - 'T1_B_2_entries_original_rate_hz'
  - 'T1_B_3_entries_original_rate_hz'
  - 'T1_B_4_entries_original_rate_hz'
  - 'Q1_F_1_entries_original_rate_hz'
  - 'Q1_F_2_entries_original_rate_hz'
  - 'Q1_F_3_entries_original_rate_hz'
  - 'Q1_F_4_entries_original_rate_hz'
  - 'Q1_B_1_entries_original_rate_hz'
  - 'Q1_B_2_entries_original_rate_hz'
  - 'Q1_B_3_entries_original_rate_hz'
  - 'Q1_B_4_entries_original_rate_hz'
  - 'T2_F_1_entries_original_rate_hz'
  - 'T2_F_2_entries_original_rate_hz'
  - 'T2_F_3_entries_original_rate_hz'
  - 'T2_F_4_entries_original_rate_hz'
  - 'T2_B_1_entries_original_rate_hz'
  - 'T2_B_2_entries_original_rate_hz'
  - 'T2_B_3_entries_original_rate_hz'
  - 'T2_B_4_entries_original_rate_hz'
  - 'Q2_F_1_entries_original_rate_hz'
  - 'Q2_F_2_entries_original_rate_hz'
  - 'Q2_F_3_entries_original_rate_hz'
  - 'Q2_F_4_entries_original_rate_hz'
  - 'Q2_B_1_entries_original_rate_hz'
  - 'Q2_B_2_entries_original_rate_hz'
  - 'Q2_B_3_entries_original_rate_hz'
  - 'Q2_B_4_entries_original_rate_hz'
  - 'T3_F_1_entries_original_rate_hz'
  - 'T3_F_2_entries_original_rate_hz'
  - 'T3_F_3_entries_original_rate_hz'
  - 'T3_F_4_entries_original_rate_hz'
  - 'T3_B_1_entries_original_rate_hz'
  - 'T3_B_2_entries_original_rate_hz'
  - 'T3_B_3_entries_original_rate_hz'
  - 'T3_B_4_entries_original_rate_hz'
  - 'Q3_F_1_entries_original_rate_hz'
  - 'Q3_F_2_entries_original_rate_hz'
  - 'Q3_F_3_entries_original_rate_hz'
  - 'Q3_F_4_entries_original_rate_hz'
  - 'Q3_B_1_entries_original_rate_hz'
  - 'Q3_B_2_entries_original_rate_hz'
  - 'Q3_B_3_entries_original_rate_hz'
  - 'Q3_B_4_entries_original_rate_hz'
  - 'T4_F_1_entries_original_rate_hz'
  - 'T4_F_2_entries_original_rate_hz'
  - 'T4_F_3_entries_original_rate_hz'
  - 'T4_F_4_entries_original_rate_hz'
  - 'T4_B_1_entries_original_rate_hz'
  - 'T4_B_2_entries_original_rate_hz'
  - 'T4_B_3_entries_original_rate_hz'
  - 'T4_B_4_entries_original_rate_hz'
  - 'Q4_F_1_entries_original_rate_hz'
  - 'Q4_F_2_entries_original_rate_hz'
  - 'Q4_F_3_entries_original_rate_hz'
  - 'Q4_F_4_entries_original_rate_hz'
  - 'Q4_B_1_entries_original_rate_hz'
  - 'Q4_B_2_entries_original_rate_hz'
  - 'Q4_B_3_entries_original_rate_hz'
  - 'Q4_B_4_entries_original_rate_hz'

  - 'T1_F_1_entries_original'
  - 'T1_F_2_entries_original'
  - 'T1_F_3_entries_original'
  - 'T1_F_4_entries_original'
  - 'T1_B_1_entries_original'
  - 'T1_B_2_entries_original'
  - 'T1_B_3_entries_original'
  - 'T1_B_4_entries_original'
  - 'Q1_F_1_entries_original'
  - 'Q1_F_2_entries_original'
  - 'Q1_F_3_entries_original'
  - 'Q1_F_4_entries_original'
  - 'Q1_B_1_entries_original'
  - 'Q1_B_2_entries_original'
  - 'Q1_B_3_entries_original'
  - 'Q1_B_4_entries_original'
  - 'T2_F_1_entries_original'
  - 'T2_F_2_entries_original'
  - 'T2_F_3_entries_original'
  - 'T2_F_4_entries_original'
  - 'T2_B_1_entries_original'
  - 'T2_B_2_entries_original'
  - 'T2_B_3_entries_original'
  - 'T2_B_4_entries_original'
  - 'Q2_F_1_entries_original'
  - 'Q2_F_2_entries_original'
  - 'Q2_F_3_entries_original'
  - 'Q2_F_4_entries_original'
  - 'Q2_B_1_entries_original'
  - 'Q2_B_2_entries_original'
  - 'Q2_B_3_entries_original'
  - 'Q2_B_4_entries_original'
  - 'T3_F_1_entries_original'
  - 'T3_F_2_entries_original'
  - 'T3_F_3_entries_original'
  - 'T3_F_4_entries_original'
  - 'T3_B_1_entries_original'
  - 'T3_B_2_entries_original'
  - 'T3_B_3_entries_original'
  - 'T3_B_4_entries_original'
  - 'Q3_F_1_entries_original'
  - 'Q3_F_2_entries_original'
  - 'Q3_F_3_entries_original'
  - 'Q3_F_4_entries_original'
  - 'Q3_B_1_entries_original'
  - 'Q3_B_2_entries_original'
  - 'Q3_B_3_entries_original'
  - 'Q3_B_4_entries_original'
  - 'T4_F_1_entries_original'
  - 'T4_F_2_entries_original'
  - 'T4_F_3_entries_original'
  - 'T4_F_4_entries_original'
  - 'T4_B_1_entries_original'
  - 'T4_B_2_entries_original'
  - 'T4_B_3_entries_original'
  - 'T4_B_4_entries_original'
  - 'Q4_F_1_entries_original'
  - 'Q4_F_2_entries_original'
  - 'Q4_F_3_entries_original'
  - 'Q4_F_4_entries_original'
  - 'Q4_B_1_entries_original'
  - 'Q4_B_2_entries_original'
  - 'Q4_B_3_entries_original'
  - 'Q4_B_4_entries_original'
  - 'T1_F_1_entries_final'
  - 'T1_F_2_entries_final'
  - 'T1_F_3_entries_final'
  - 'T1_F_4_entries_final'
  - 'T1_B_1_entries_final'
  - 'T1_B_2_entries_final'
  - 'T1_B_3_entries_final'
  - 'T1_B_4_entries_final'
  - 'Q1_F_1_entries_final'
  - 'Q1_F_2_entries_final'
  - 'Q1_F_3_entries_final'
  - 'Q1_F_4_entries_final'
  - 'Q1_B_1_entries_final'
  - 'Q1_B_2_entries_final'
  - 'Q1_B_3_entries_final'
  - 'Q1_B_4_entries_final'
  - 'T2_F_1_entries_final'
  - 'T2_F_2_entries_final'
  - 'T2_F_3_entries_final'
  - 'T2_F_4_entries_final'
  - 'T2_B_1_entries_final'
  - 'T2_B_2_entries_final'
  - 'T2_B_3_entries_final'
  - 'T2_B_4_entries_final'
  - 'Q2_F_1_entries_final'
  - 'Q2_F_2_entries_final'
  - 'Q2_F_3_entries_final'
  - 'Q2_F_4_entries_final'
  - 'Q2_B_1_entries_final'
  - 'Q2_B_2_entries_final'
  - 'Q2_B_3_entries_final'
  - 'Q2_B_4_entries_final'
  - 'T3_F_1_entries_final'
  - 'T3_F_2_entries_final'
  - 'T3_F_3_entries_final'
  - 'T3_F_4_entries_final'
  - 'T3_B_1_entries_final'
  - 'T3_B_2_entries_final'
  - 'T3_B_3_entries_final'
  - 'T3_B_4_entries_final'
  - 'Q3_F_1_entries_final'
  - 'Q3_F_2_entries_final'
  - 'Q3_F_3_entries_final'
  - 'Q3_F_4_entries_final'
  - 'Q3_B_1_entries_final'
  - 'Q3_B_2_entries_final'
  - 'Q3_B_3_entries_final'
  - 'Q3_B_4_entries_final'
  - 'T4_F_1_entries_final'
  - 'T4_F_2_entries_final'
  - 'T4_F_3_entries_final'
  - 'T4_F_4_entries_final'
  - 'T4_B_1_entries_final'
  - 'T4_B_2_entries_final'
  - 'T4_B_3_entries_final'
  - 'T4_B_4_entries_final'
  - 'Q4_F_1_entries_final'
  - 'Q4_F_2_entries_final'
  - 'Q4_F_3_entries_final'
  - 'Q4_F_4_entries_final'
  - 'Q4_B_1_entries_final'
  - 'Q4_B_2_entries_final'
  - 'Q4_B_3_entries_final'
  - 'Q4_B_4_entries_final'

plots:
  zeroed_grid:
    nrows: 4
    ncols: 4
    figsize: [18, 12]
  entries_grid:
    nrows: 8
    ncols: 4
    figsize: [18, 24]
    # If all Q*_entries_*_rate_hz values are identical to T*_entries_*_rate_hz,
    # the Q figure is skipped to avoid redundant output.
    skip_q_if_identical_to_t: true
  dpi: 150
  line_width: 0.9
  marker_size: 2.0
  format: png
