% =============================================================================
% DATAFLOW_v3 Script Header v1
% Script: MASTER/STAGES/STAGE_0/REPROCESSING/UNPACKER_ZERO_STAGE_FILES/system/lookUpTables/lookUpTables_RPC.m
% Purpose: LookUpTables RPC.
% Owner: DATAFLOW_v3 contributors
% Sign-off: csoneira <csoneira@ucm.es>
% Last Updated: 2026-03-02
% Runtime: octave/matlab
% Usage: Run from MATLAB/Octave entrypoint with expected args/context.
% Inputs: Variables, config files, environment, and/or upstream files.
% Outputs: Variables, files, plots, or logs.
% Notes: Keep behavior configuration-driven and reproducible.
% =============================================================================

%
%
%
%
%
chf = [8 7 6 5];
chb = [4 3 2 1];

lookUpInstructions = {...
                      'T1_F', '                                      F_C001(:,      (2 + 24 + chf))';...
                      'T1_B', '                                      F_C001(:,      (2 + 24 + chb))';...
                      'Q1_F', 'F_C001(:,  (2 + 64 + 24 + chf))     - F_C001(:,      (2 + 24 + chf))';...
                      'Q1_B', 'F_C001(:,  (2 + 64 + 24 + chb))     - F_C001(:,      (2 + 24 + chb))';...
                      'T2_F', '                                      F_C001(:,      (2 + 16 + chf))';...
                      'T2_B', '                                      F_C001(:,      (2 + 16 + chb))';...
                      'Q2_F', 'F_C001(:,  (2 + 64 + 16 + chf))     - F_C001(:,      (2 + 16 + chf))';...
                      'Q2_B', 'F_C001(:,  (2 + 64 + 16 + chb))     - F_C001(:,      (2 + 16 + chb))';...
                      'T3_F', '                                      F_C001(:,      (2 + 08 + chf))';...
                      'T3_B', '                                      F_C001(:,      (2 + 08 + chb))';...
                      'Q3_F', 'F_C001(:,  (2 + 64 + 08 + chf))     - F_C001(:,      (2 + 08 + chf))';...
                      'Q3_B', 'F_C001(:,  (2 + 64 + 08 + chb))     - F_C001(:,      (2 + 08 + chb))';...
                      'T4_F', '                                      F_C001(:,      (2 + 00 + chf))';...
                      'T4_B', '                                      F_C001(:,      (2 + 00 + chb))';...
                      'Q4_F', 'F_C001(:,  (2 + 64 + 00 + chf))     - F_C001(:,      (2 + 00 + chf))';...
                      'Q4_B', 'F_C001(:,  (2 + 64 + 00 + chb))     - F_C001(:,      (2 + 00 + chb))';...
                      %'filePosition'    ,'a_HEAD;';...
                      %'fileNames'       ,'b_HEAD;';...
                      'EBtime'          ,'c_HEAD;';... 
                      'triggerType'     ,'d_HEAD;';...
                       };