selection:
  stations: [0, 1]
  date_ranges:
    - start: 2024-09-16
      end: 2024-09-30

reprocessing_run_matrix:
  enabled: true
  mode: whitelist
  default_steps: []
  stations:
    "0": [0, 1, 2]
    "1": [0, 1, 2]
    #"2": [0, 1, 2]
    #"3": [0, 1, 2]
    #"4": [0, 1, 2]
