stations: [0, 1, 2, 3, 4]
task_id: 1
metadata_type: filtering
metadata_csv_filename: task_1_metadata_filter.csv
column_patterns_file: task_1_filtering_columns.txt
pass_default_value: 1.0
pass_column_name: task_1_filtering_pass
column_patterns:
  - 'filename_base'
  - 'execution_timestamp'
  - 'param_hash'
  - 'plane_combination_filter_rows_affected_pct'
  - 'plane_combination_filter_rows_with_self_relation_failures_pct'
  - 'plane_combination_filter_rows_with_same_strip_relation_failures_pct'
  - 'plane_combination_filter_rows_with_same_plane_relation_failures_pct'
  - 'plane_combination_filter_rows_with_any_relation_failures_pct'
  - 'clean_tt_lt_10_rows_removed_pct'
  - 'valid_lines_in_binary_file_percentage'
  - 'data_purity_percentage'
plots:
  ncols: 3
  plot_groups:
    - name: filtering_core
      columns:
        - 'plane_combination_filter_rows_affected_pct'
        - 'plane_combination_filter_rows_with_self_relation_failures_pct'
        - 'plane_combination_filter_rows_with_same_strip_relation_failures_pct'
        - 'plane_combination_filter_rows_with_same_plane_relation_failures_pct'
        - 'plane_combination_filter_rows_with_any_relation_failures_pct'
        - 'clean_tt_lt_10_rows_removed_pct'
    - name: data_purity
      columns:
        - 'valid_lines_in_binary_file_percentage'
        - 'data_purity_percentage'
