stations: [0, 1, 2, 3, 4]
task_id: 2
metadata_type: filtering
metadata_csv_filename: task_2_metadata_filter.csv
column_patterns_file: task_2_filtering_columns.txt
pass_default_value: 1.0
pass_column_name: task_2_filtering_pass
column_patterns:
  - 'filename_base'
  - 'execution_timestamp'
  - 'param_hash'
  - 'precal_strip_window_rows_affected_pct'
  - 'calibrated_t_dif_rows_affected_pct'
  - 'calibrated_q_dif_rows_affected_pct'
  - 'calibrated_q_sum_rows_affected_pct'
  - 'front_back_q_dif_rows_affected_pct'
  - 'calibrated_t_sum_rows_affected_pct'
  - 'post_crosstalk_q_sum_rows_affected_pct'
  - 'strip_combination_filter_rows_affected_pct'
  - 'q_sum_all_zero_rows_removed_pct'
  - 'all_components_zero_rows_removed_pct'
  - 'cal_tt_lt_10_rows_removed_pct'
  - 'data_purity_percentage'
plots:
  ncols: 4
  plot_groups:
    - name: filtering_core
      columns:
        - 'precal_strip_window_rows_affected_pct'
        - 'calibrated_t_dif_rows_affected_pct'
        - 'calibrated_q_dif_rows_affected_pct'
        - 'calibrated_q_sum_rows_affected_pct'
        - 'front_back_q_dif_rows_affected_pct'
        - 'calibrated_t_sum_rows_affected_pct'
        - 'post_crosstalk_q_sum_rows_affected_pct'
        - 'strip_combination_filter_rows_affected_pct'
        - 'q_sum_all_zero_rows_removed_pct'
        - 'all_components_zero_rows_removed_pct'
        - 'cal_tt_lt_10_rows_removed_pct'
    - name: data_purity
      columns:
        - 'data_purity_percentage'
