create_new_csv: true
outlier_limits:
  rates_Asserted:
  - 0
  - 60
  rates_Edge:
  - 0
  - 45
  rates_Accepted:
  - 0
  - 30
  rates_Multiplexer1:
  - 0
  - 400
  rates_M2:
  - 0
  - 400
  rates_M3:
  - 0
  - 400
  rates_M4:
  - 0
  - 400
  rates_CM1:
  - 0
  - 30
  rates_CM2:
  - 0
  - 30
  rates_CM3:
  - 0
  - 30
  rates_CM4:
  - 0
  - 30
  sensors_ext_Temperature_ext:
  - 0
  - 50
  sensors_ext_RH_ext:
  - 0
  - 100
  sensors_ext_Pressure_ext:
  - 500
  - 1300
  sensors_int_Temperature_int:
  - 0
  - 100
  sensors_int_RH_int:
  - 0
  - 100
  sensors_int_Pressure_int:
  - 500
  - 1300
  odroid_DiskFill1:
  - 0
  - 100
  odroid_DiskFill2:
  - 0
  - 100
  odroid_DiskFillX:
  - 0
  - 100000
  flow_FlowRate1:
  - 0
  - 1500
  flow_FlowRate2:
  - 0
  - 1500
  flow_FlowRate3:
  - 0
  - 1500
  flow_FlowRate4:
  - 0
  - 1500
  hv_HVneg:
  - -0.1
  - 20
  hv_HVpos:
  - -0.1
  - 20
