plots:
  debug_suite: debug
  usual_suite: usual
  essential_suite: essential
  all_channels_charge: usual
  flat_values_histogram: usual
  detached_timeseries_combo: usual
  detached_residuals_combo: usual
  timtrack_timeseries_combo: usual
  timtrack_residuals_combo: usual
  combined_timeseries_combo: usual
  combined_residuals_combo: usual
  hist_core_errs_combined: usual
  hist_core_errs_combined_with_fits: usual
  stat_window_accumulation: usual
  trigger_types_raw_and_list: usual
  trigger_types_tracking_and_list: usual
  trigger_types_tracking_and_raw: usual
  trigger_types_definitive_tt_and_raw: usual
  timtrack_results_hexbin_combination_projections: usual
  timtrack_results_scatter_combination_projections: usual
  theta_det_theta_zoom_tracking_tt: usual
  polar_theta_phi_definitive_tt_2d: usual
  polar_theta_phi_tracking_tt_2d: usual
  events_per_second_by_plane_cardinality_double_row: usual
  timtrack_residuals_gaussian: usual
  tim_th_chi_sigmafit_1234_histogram: usual
  external_residuals_gaussian: usual
  event_display_sample: usual
  track_consistency_loo_residuals: usual
  strip_hit_occupancy: essential
  track_based_efficiency: essential
  total_event_charge_histogram: usual
  track_based_efficiency_tt_stability: usual
  track_based_efficiency_vs_theta: usual
  timtrack_projection_ellipse_contours: usual
  timtrack_projection_scaled_angle_comparison: usual
  chi2_offender_populations: usual
  offender_angle_populations: usual
  offender_kinematics_populations: usual
  offender_tt_balance: usual
  offender_zigzag_populations: usual
  chi2_charge_populations: usual
  chi2_residuals_populations: usual
  event_display_sample_3fold: usual
  chi2_charge_populations_3fold: usual
  chi2_residuals_populations_3fold: usual
  adj_dis_comparison: usual
