crontab_execution: true
last_file_test: true
selection:
  stations: [0, 1]
  date_ranges:
    - start: 2024-09-16
      end: 2024-09-30
self_trigger: false
timeseries_and_fits: false
complete_reanalysis: false
# create_plots options: null | debug | usual | all
create_plots: null
save_rejected_rows: false
create_reject_plots: false
limit_number: null
alternative_iteration: false
number_of_det_executions: 2
fixed_speed: false
res_ana_removing_planes: true
timtrack_iteration: true
number_of_TT_executions: 1
