stations: [0, 1, 2, 3, 4]
task_id: 5
metadata_type: filtering
metadata_csv_filename: task_5_metadata_filter.csv
column_patterns_file: task_5_filtering_columns.txt
pass_default_value: 1.0
pass_column_name: task_5_filtering_pass
column_patterns:
  - 'filename_base'
  - 'execution_timestamp'
  - 'param_hash'
  - 'total_rows_removed_pct'
  - 'all_components_zero_rows_removed_pct'
  - 'corr_tt_lt_10_rows_removed_pct'
  - 'data_purity_percentage'
plots:
  ncols: 4
  plot_groups:
    - name: filtering_core
      columns:
        - 'total_rows_removed_pct'
        - 'all_components_zero_rows_removed_pct'
        - 'corr_tt_lt_10_rows_removed_pct'
    - name: data_purity
      columns:
        - 'data_purity_percentage'
