correct_angle: false
last_file_test: true
update_big_event_file: false
multiple_files: true
run_jupyter_notebook: false
remove_outliers: true
create_plots: false
create_essential_plots: false
save_plots: true
create_pdf: false
force_replacement: true
show_plots: false
side_calculations: false
eff_vs_charge: false
eff_vs_angle_and_pos: false
noise_vs_angle: false
noise_2d: false
charge_vs_angle: false
polya_fit: false
real_strip_case_study: false
multiplicity_calculations: false
crosstalk_probability: false
n_study_fit: false
topology_plots: false
cluster_of_files: 0
time_window_in_hours: 10
time_tolerance_in_minutes: 10
three_plane_eff: false
crosstalk_limit: 1
streamer_limit: 100
complete_reanalysis: false
q_e: 0.0001602
blurring_angular: true
blurring_sigma_angular: 2
blurring_xy: false
blurring_sigma_xy: 0.05
draw_angular_regions: true
theta_boundaries: [5, 15, 25]
region_layout: [1, 8, 8, 8]
time_to_min: false
