input_dir: ../../SIMULATION_OUTPUTS/INTERSTEPS/STEP_8_TO_9
input_glob: "**/step_8_chunks.chunks.json"
input_sim_run: random
output_format: pkl
output_dir: ../../SIMULATION_OUTPUTS/INTERSTEPS/STEP_9_TO_10
chunk_rows: 50000
plot_sample_rows: true
