% =============================================================================
% DATAFLOW_v3 Script Header v1
% Script: MASTER/STAGES/STAGE_0/REPROCESSING/UNPACKER_ZERO_STAGE_FILES/software/conf/initDevice.m
% Purpose: initDevice function implementation.
% Owner: DATAFLOW_v3 contributors
% Sign-off: csoneira <csoneira@ucm.es>
% Last Updated: 2026-03-02
% Runtime: octave/matlab
% Usage: Run from MATLAB/Octave entrypoint with expected args/context.
% Inputs: Variables, config files, environment, and/or upstream files.
% Outputs: Variables, files, plots, or logs.
% Notes: Keep behavior configuration-driven and reproducible.
% =============================================================================

function dev = initDevice()

dev = struct(...
               'active',[],...
               'name','',...
               'subName','',...
               'type','',...
               'subType','',...
               'reportable',struct('active',[],'LT','','timeElapsed',''),...
               'path',struct('base','','data',''),...
               'dcs',struct('active',[],'readable',[],...
                            'rAccess',struct('active',[],'IP','','port','','user','','key','','fileExt',[],'remotePath','','keepData','','zipData','','filesLeft',''),...
                            'lAccess',struct('active',[]),...
                            'dcData2MatScript','',...
                            'distributionLT','',...
                            'path',struct('base','','rawData','','rawDataDat','','rawDataMat','','data','','LT','')...
                            ),...
               'ana',struct('active',[],...  
                            'path',struct('base','')...
                            )...
             );               
return
