% =============================================================================
% DATAFLOW_v3 Script Header v1
% Script: MASTER/STAGES/STAGE_0/REPROCESSING/UNPACKER_ZERO_STAGE_FILES/software/conf/initDAQ.m
% Purpose: initDAQ function implementation.
% Owner: DATAFLOW_v3 contributors
% Sign-off: csoneira <csoneira@ucm.es>
% Last Updated: 2026-03-02
% Runtime: octave/matlab
% Usage: Run from MATLAB/Octave entrypoint with expected args/context.
% Inputs: Variables, config files, environment, and/or upstream files.
% Outputs: Variables, files, plots, or logs.
% Notes: Keep behavior configuration-driven and reproducible.
% =============================================================================

function daq = initDAQ()

daq = struct(...
             'active',[],...   
             'name','',...
             'subName','',...
             'path',struct('base','','data',''),... 
             'readable',[],...
             'rAccess',struct('active',[],'IP','','user','','fileExt','','remotePath','','port',''),...
             'lAccess',struct('active',[],'fileExt','','path','','zip',[]),...
             'unpacking',struct('path',struct('base','','rawData','','rawDataDat','','rawDataMat',''),'fileExt','','bufferSize','','type','','keepHLDs','','writeTDCCal',[]),...
             'raw2var',struct('path',struct('base','','varData','','lookUpTables',''),'lookUpTables','','keepRawFiles',[]),...
             'var2cal',struct('path',struct('base','','calData','','lookUpTables',''),'lookUpTables','','keepVarFiles',[]),...
             'out',struct(),...
             'TRB3',struct('active',[],'type','','centralFPGA','','FPGAs',[]),...    
             'TRB2',struct('active',[])...    
             );               
return


