version: 1

gates:
  charge_gt_10:
    bit: 0
    description: "Events with charge_event greater than 10"
    expression: "(charge_event > 10)"

  charge_gt_10_s_abs_lt_0p0006:
    bit: 1
    description: "Events with charge_event greater than 10 and abs(s) lower than 0.0006"
    expression: "(charge_event > 10) & (s > -0.0006) & (s < 0.0006)"
  
  charge_gt_10_s_abs_lt_0p0012:
    bit: 2
    description: "Events with charge_event greater than 10 and abs(s) lower than 0.0012"
    expression: "(charge_event > 10) & (s > -0.0012) & (s < 0.0012)"
  
  charge_gt_10_s_abs_lt_0p0024:
    bit: 3
    description: "Events with charge_event greater than 10 and abs(s) lower than 0.0024"
    expression: "(charge_event > 10) & (s > -0.0024) & (s < 0.0024)"
  
  chisq_filter:
    bit: 4
    description: "Events with tim_th_chi_sigmafit_1234 lower than 40"
    expression: "(tim_th_chi_sigmafit_1234 < 40)"