selection:
  station_base_dir: "/home/mingo/DATAFLOW_v3/STATIONS"
  stations:
    - "MINGO02"
  input_subdir: "STAGE_1/EVENT_DATA/STEP_2/INPUT_FILES/COMPLETED"
  start_datetime: "2026-05-09T00:00:00"
  end_datetime: "2026-07-07T00:00:00"
  output_dir: "/home/mingo/DATAFLOW_v3/MASTER/STAGES/STAGE_1/EVENT_DATA/STEP_2_DETOUR/outputs"

rate_output:
  enabled: true
  time_column: "Time"
  bin_size: "1min"
  output_file: "rates/gate_rates_per_minute.parquet"
  moving_average_minutes: 5

plotting:
  enabled: true
  gate_columns: []
  output_file: "plots"
  rate_mode: "rates"  # options: "rates" or "zscores"
