logbook:
  sheet_id: 1ato36QkIXCxFkDT_LtAaLjPP7pvLcor-xZAP4fy00l0
  gid_by_station:
    '1': 1331842924
    '2': 600987525
    '3': 376764978
    '4': 1268265225

new_files_run_matrix:
  enabled: true

selection:
  stations: [0, 1]
  date_ranges:
    - start: 2024-09-16
      end: 2024-09-30
