logbook:
  sheet_id: 1ato36QkIXCxFkDT_LtAaLjPP7pvLcor-xZAP4fy00l0
  gid_by_station:
    '1': 1331842924
    '2': 600987525
    '3': 376764978
    '4': 1268265225

new_files_run_matrix:
  enabled: true
  mode: whitelist
  default_stations: []
  stations: [1, 2, 3, 4]

date_ranges: []
