stations: [0, 1, 2, 3, 4]
task_id: 4
metadata_type: filtering
metadata_csv_filename: task_4_metadata_filter.csv
column_patterns_file: task_4_filtering_columns.txt
pass_default_value: 1.0
pass_column_name: task_4_filtering_pass
column_patterns:
  - 'filename_base'
  - 'execution_timestamp'
  - 'param_hash'
  - 'det_residual_zeroed_event_pct'
  - 'det_bounds_zeroed_event_pct'
  - 'residual_zeroed_event_pct'
  - 'small_values_zeroed_event_pct'
  - 'small_values_zeroed_value_pct'
  - 'definitive_small_values_zeroed_event_pct'
  - 'definitive_small_values_zeroed_value_pct'
  - 'low_tt_zeroed_event_pct'
  - 'definitive_rows_removed_pct'
  - 'definitive_removed_single_zero_rows_pct'
  - 'definitive_removed_multi_zero_rows_pct'
  - 'definitive_removed_primary_x_zero_rows_pct'
  - 'definitive_removed_primary_y_zero_rows_pct'
  - 'definitive_removed_primary_s_zero_rows_pct'
  - 'definitive_removed_primary_t0_zero_rows_pct'
  - 'definitive_removed_primary_theta_zero_rows_pct'
  - 'definitive_removed_primary_phi_zero_rows_pct'
  - 'definitive_x_zero_rows_pct'
  - 'definitive_y_zero_rows_pct'
  - 'definitive_s_zero_rows_pct'
  - 'definitive_t0_zero_rows_pct'
  - 'definitive_theta_zero_rows_pct'
  - 'definitive_phi_zero_rows_pct'
  - 'ancillary_charge_filtered_rows_pct'
  - 'all_components_zero_rows_removed_pct'
  - 'fit_tt_lt_10_rows_removed_pct'
  - 'data_purity_percentage'
plots:
  ncols: 4
  plot_groups:
    - name: filtering_core
      columns:
        - 'det_residual_zeroed_event_pct'
        - 'det_bounds_zeroed_event_pct'
        - 'residual_zeroed_event_pct'
        - 'small_values_zeroed_event_pct'
        - 'small_values_zeroed_value_pct'
        - 'definitive_small_values_zeroed_event_pct'
        - 'definitive_small_values_zeroed_value_pct'
        - 'low_tt_zeroed_event_pct'
        - 'definitive_rows_removed_pct'
        - 'definitive_removed_single_zero_rows_pct'
        - 'definitive_removed_multi_zero_rows_pct'
        - 'definitive_removed_primary_x_zero_rows_pct'
        - 'definitive_removed_primary_y_zero_rows_pct'
        - 'definitive_removed_primary_s_zero_rows_pct'
        - 'definitive_removed_primary_t0_zero_rows_pct'
        - 'definitive_removed_primary_theta_zero_rows_pct'
        - 'definitive_removed_primary_phi_zero_rows_pct'
        - 'definitive_x_zero_rows_pct'
        - 'definitive_y_zero_rows_pct'
        - 'definitive_s_zero_rows_pct'
        - 'definitive_t0_zero_rows_pct'
        - 'definitive_theta_zero_rows_pct'
        - 'definitive_phi_zero_rows_pct'
        - 'ancillary_charge_filtered_rows_pct'
        - 'all_components_zero_rows_removed_pct'
        - 'fit_tt_lt_10_rows_removed_pct'
    - name: data_purity
      columns:
        - 'data_purity_percentage'
