selection:
  stations: [0, 1]
  date_ranges:
    - start: 2024-09-27
      end: 2024-10-01

backup_restore:
  enabled: true
  local_log_backup_root: /home/mingo/DATAFLOW_v3/LOG_BACKUP
  ssh_host: ana
  station_dump_paths:
    1: /home/rpcuser/db_backups/mingo01/mingo01.tar
