stations: [1]
task_id: 1
metadata_type: trigger_types
metadata_csv_filename: task_1_metadata_trigger_type.csv
column_patterns_file: task_1_trigger_types_columns.txt
pass_default_value: 1.0
pass_column_name: task_1_trigger_types_pass
column_patterns:
  - 'filename_base'
  - 'execution_timestamp'
  - 'raw_tt_12_rate_hz'
  - 'raw_tt_124_rate_hz'
  - 'raw_tt_123_rate_hz'
  - 'raw_tt_23_rate_hz'
  - 'raw_tt_13_rate_hz'
  - 'raw_tt_34_rate_hz'
  - 'raw_tt_1234_rate_hz'
  - 'raw_tt_234_rate_hz'
  - 'raw_tt_134_rate_hz'
  - 'clean_tt_12_rate_hz'
  - 'clean_tt_124_rate_hz'
  - 'clean_tt_123_rate_hz'
  - 'clean_tt_23_rate_hz'
  - 'clean_tt_13_rate_hz'
  - 'clean_tt_34_rate_hz'
  - 'clean_tt_1234_rate_hz'
  - 'clean_tt_234_rate_hz'
  - 'clean_tt_134_rate_hz'
  - 'raw_to_clean_tt_12_12_rate_hz'
  - 'raw_to_clean_tt_124_124_rate_hz'
  - 'raw_to_clean_tt_123_123_rate_hz'
  - 'raw_to_clean_tt_23_23_rate_hz'
  - 'raw_to_clean_tt_13_13_rate_hz'
  - 'raw_to_clean_tt_34_34_rate_hz'
  - 'raw_to_clean_tt_1234_1234_rate_hz'
  - 'raw_to_clean_tt_234_234_rate_hz'
  - 'raw_to_clean_tt_134_134_rate_hz'
  - 'raw_tt_0_rate_hz'
  - 'raw_tt_1_rate_hz'
  - 'raw_tt_2_rate_hz'
  - 'raw_tt_3_rate_hz'
  - 'raw_tt_4_rate_hz'
  - 'raw_tt_14_rate_hz'
  - 'raw_tt_24_rate_hz'
  - 'clean_tt_0_rate_hz'
  - 'clean_tt_1_rate_hz'
  - 'clean_tt_2_rate_hz'
  - 'clean_tt_3_rate_hz'
  - 'clean_tt_4_rate_hz'
  - 'clean_tt_14_rate_hz'
  - 'clean_tt_24_rate_hz'
  - 'raw_to_clean_tt_0_rate_hz'
  - 'raw_to_clean_tt_1_rate_hz'
  - 'raw_to_clean_tt_2_rate_hz'
  - 'raw_to_clean_tt_3_rate_hz'
  - 'raw_to_clean_tt_4_rate_hz'
  - 'raw_to_clean_tt_12_rate_hz'
  - 'raw_to_clean_tt_13_rate_hz'
  - 'raw_to_clean_tt_14_rate_hz'
  - 'raw_to_clean_tt_23_rate_hz'
  - 'raw_to_clean_tt_24_rate_hz'
  - 'raw_to_clean_tt_34_rate_hz'
  - 'raw_to_clean_tt_123_rate_hz'
  - 'raw_to_clean_tt_124_rate_hz'
  - 'raw_to_clean_tt_134_rate_hz'
  - 'raw_to_clean_tt_234_rate_hz'
  - 'raw_to_clean_tt_1234_rate_hz'
  - 'raw_to_clean_tt_234_34_rate_hz'
  - 'raw_to_clean_tt_1234_134_rate_hz'
  - 'count_rate_denominator_seconds'
  - 'raw_to_clean_tt_124_12_rate_hz'
  - 'raw_to_clean_tt_234_23_rate_hz'
  - 'raw_to_clean_tt_134_13_rate_hz'
  - 'raw_to_clean_tt_123_12_rate_hz'
  - 'raw_to_clean_tt_124_24_rate_hz'
  - 'raw_to_clean_tt_123_23_rate_hz'
  - 'raw_to_clean_tt_134_34_rate_hz'
  - 'raw_to_clean_tt_1234_234_rate_hz'
  - 'raw_to_clean_tt_234_24_rate_hz'
  - 'raw_to_clean_tt_123_13_rate_hz'
  - 'raw_to_clean_tt_1234_123_rate_hz'
  - 'raw_to_clean_tt_1234_124_rate_hz'
  - 'raw_tt_1234_count'
  - 'raw_tt_12_count'
  - 'raw_tt_34_count'
  - 'raw_tt_123_count'
  - 'raw_tt_234_count'
  - 'raw_tt_23_count'
  - 'raw_tt_134_count'
  - 'raw_tt_124_count'
  - 'raw_tt_13_count'
  - 'clean_tt_1234_count'
  - 'clean_tt_12_count'
  - 'clean_tt_34_count'
  - 'clean_tt_123_count'
  - 'clean_tt_234_count'
  - 'clean_tt_23_count'
  - 'clean_tt_124_count'
  - 'clean_tt_134_count'
  - 'clean_tt_13_count'
  - 'clean_tt_24_count'
  - 'raw_to_clean_tt_1234_1234_count'
  - 'raw_to_clean_tt_12_12_count'
  - 'raw_to_clean_tt_34_34_count'
  - 'raw_to_clean_tt_123_123_count'
  - 'raw_to_clean_tt_234_234_count'
  - 'raw_to_clean_tt_23_23_count'
  - 'raw_to_clean_tt_1234_124_count'
  - 'raw_to_clean_tt_134_134_count'
  - 'raw_to_clean_tt_124_124_count'
  - 'raw_to_clean_tt_13_13_count'
  - 'raw_to_clean_tt_1234_234_count'
  - 'raw_to_clean_tt_1234_123_count'
  - 'raw_to_clean_tt_234_34_count'
  - 'raw_to_clean_tt_123_12_count'
  - 'raw_to_clean_tt_1234_12_count'
  - 'raw_to_clean_tt_1234_134_count'
  - 'raw_to_clean_tt_1234_34_count'
  - 'raw_to_clean_tt_1234_24_count'
  - 'raw_to_clean_tt_234_23_count'
  - 'raw_to_clean_tt_123_13_count'
  - 'raw_to_clean_tt_123_23_count'
  - 'raw_to_clean_tt_234_24_count'
  - 'raw_to_clean_tt_1234_12_rate_hz'
  - 'raw_to_clean_tt_1234_34_rate_hz'
  - 'raw_to_clean_tt_1234_24_rate_hz'
  - 'raw_to_clean_tt_1234_23_count'
  - 'raw_to_clean_tt_1234_13_count'
  - 'raw_to_clean_tt_134_34_count'
  - 'raw_to_clean_tt_1234_23_rate_hz'
  - 'raw_to_clean_tt_1234_13_rate_hz'
  - 'raw_to_clean_tt_124_12_count'
  - 'raw_to_clean_tt_124_24_count'
  - 'raw_to_clean_tt_134_13_count'
  - 'clean_tt_14_count'
  - 'raw_to_clean_tt_124_14_count'
  - 'raw_to_clean_tt_1234_14_count'
  - 'raw_to_clean_tt_134_14_count'
  - 'raw_to_clean_tt_124_14_rate_hz'
  - 'raw_to_clean_tt_1234_14_rate_hz'
  - 'raw_to_clean_tt_134_14_rate_hz'
  - 'raw_tt_3_count'
  - 'raw_tt_4_count'
  - 'raw_tt_24_count'
  - 'raw_tt_1_count'
  - 'raw_tt_2_count'
  - 'raw_tt_14_count'

plots:
  plot_groups:
    - name: raw_vs_clean_rates
      overlay_columns:
        - raw_tt_*_rate_hz
        - clean_tt_*_rate_hz
      overlay_labels:
        - raw
        - clean
    - name: raw_to_clean_rates
      columns:
        - raw_to_clean_tt_*_rate_hz
  ncols: 4
  dpi: 150
  format: png
