selection:
  # Non-empty list overrides station selection in lower-level configs.
  stations: [0, 1]
  # Non-empty list overrides date range selection in lower-level configs.
  date_ranges:
    - start: 2024-09-01 00:00:00 # 2024-09-27
      end: 2024-10-07 12:00:00 # 2024-09-30
