selection:
  # Non-empty list overrides station selection in lower-level configs.
  stations: [0]
  # Non-empty list overrides date range selection in lower-level configs.
  date_ranges:
    - start: 2024-09-16
      end: 2024-09-30
