selection:
  # Non-empty list overrides station selection in lower-level configs.
  stations: [0, 1]
  # Non-empty list overrides date range selection in lower-level configs.
  date_ranges:
    - start: 2024-09-28 03:00:00 # 2024-09-27 mingo01_task1_2024.09.28_03.07.35
      end: 2024-09-28 03:10:00 # 2024-09-30
